// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-8oITPsUYjvYgtgI0pTYGyOTFlvxRcM',
    appId: '1:466296971483:web:26e44b5c82678ea156acfe',
    messagingSenderId: '466296971483',
    projectId: 'makeover-3d213',
    authDomain: 'makeover-3d213.firebaseapp.com',
    databaseURL: 'https://makeover-3d213.firebaseio.com',
    storageBucket: 'makeover-3d213.appspot.com',
    measurementId: 'G-ZCDSWYXQRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5E9VSoMdn5O6dLQiqxYcfEy1r4b7wRc',
    appId: '1:466296971483:android:b7a7fe372853a84256acfe',
    messagingSenderId: '466296971483',
    projectId: 'makeover-3d213',
    databaseURL: 'https://makeover-3d213.firebaseio.com',
    storageBucket: 'makeover-3d213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRbQDChzPvZzj0rHOCybtPpE_uPnGi2Q',
    appId: '1:466296971483:ios:704d4f87f6fcd1bc56acfe',
    messagingSenderId: '466296971483',
    projectId: 'makeover-3d213',
    databaseURL: 'https://makeover-3d213.firebaseio.com',
    storageBucket: 'makeover-3d213.appspot.com',
    androidClientId: '466296971483-fm1320rr4vp0mit6fjndhh7l4b349b6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tonyWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRbQDChzPvZzj0rHOCybtPpE_uPnGi2Q',
    appId: '1:466296971483:ios:a338bc3104d2ac1856acfe',
    messagingSenderId: '466296971483',
    projectId: 'makeover-3d213',
    databaseURL: 'https://makeover-3d213.firebaseio.com',
    storageBucket: 'makeover-3d213.appspot.com',
    androidClientId: '466296971483-fm1320rr4vp0mit6fjndhh7l4b349b6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tonyWeb.RunnerTests',
  );
}
